### ISSUE TITLE
Google map link not working

### ISSUE THREAD

**Issue by Expooo7** [jakubvalenta/geoshare#122]
### Map URL (Google Maps, Apple Maps etc.)

https://maps.app.goo.gl/EbhWBX4fpnqDkaSG7?g_st=ipc

### Current behaviour

If I click on this link from whatsapp geoshare says "Unsupported map service".
If I paste the link in the app manually it crashes after showing that it's trying to connect to Google.

### Version

Geo-share 5.0.0

### Android

Latest

**Comment by jakubvalenta** [comment]
Thanks for reporting the issue.

- The Unsupported map service problem will be easier to debug with v5.2.0, because this version will show on the error screen the URL that Geo Share tried to process.
- The crash is probably #112. It has been fixed in v5.2.0.

I will comment here once v5.2.0 is available on F-Droid so you can try it again.

**Comment by jakubvalenta** [comment]
Version 5.2.0 is now available on F-Droid and other channels.

- If you could update the app and try sharing the link from WhatsApp again and send a screenshot of the error screen, it would be very helpful.
- Regarding the crash, it should be fixed.

**Comment by Expooo7** [comment]
I have updated the app.
When pasting the maps.app.goo.gl link into geoshare it works!
But when clicking on the link directly from the whatsapp app it still doesnt work. Probably something about redirection. Even if i paste it into obsidian notes and open it from there it doesnt work.

What is weird is that from the short link geoshare does indeed generate a large link which if pasted into webbrowsers is correct gmaps link. But the app can't decipher it.

Screenshots attached

![Screenshot_20250924_193754_Geo Share.jpg](https://github.com/user-attachments/assets/5b12c555-84d3-4e15-b821-7e275c1f4743)

Easier access to the displayed link:

https://maps.google.com?q=Via+Giosu%C3%A8+Carducci,+27,+24127+Bergamo+BG&ftid=0x4781517434094b29:0xc5c9e7f8aaae65cd&entry=gps&lucs=,94284499,94224825,94227247,94227248,94231188,47071704,47069508,94218641,94282134,94203019,47084304&g_ep=CAISEjI1LjM1LjAuNzk5MDg4MzU1MBgAINeCAypjLDk0Mjg0NDk5LDk0MjI0ODI1LDk0MjI3MjQ3LDk0MjI3MjQ4LDk0MjMxMTg4LDQ3MDcxNzA0LDQ3MDY5NTA4LDk0MjE4NjQxLDk0MjgyMTM0LDk0MjAzMDE5LDQ3MDg0MzA0QgJJVA%3D%3D&skid=1eeafc37-ff36-40c5-834e-c4fea103bbeb&g_st=ipc&g_st=ipc

**Comment by jakubvalenta** [comment]
That was very useful information, thanks! The issue has been fixed in #137. I will comment here when the release is available on F-Droid.

**Comment by jakubvalenta** [comment]
Version 5.3.0, which contains the fix, is now available on F-Droid.

By the way, if you use Google Play and would like to help Geo Share get published there, you can write me an email to `jakub at jakubvalenta dot cz` and I'll invite you to the testing program. It's one of Google's requirements for the approval of the app, that a few people install the testing version.

**Comment by Expooo7** [comment]
I don't know if it's worth it launching an app on the Play Store if Google wishes to employ the Android Developer Verification. If google backs down from that idiotic decision, i'll gladly help your app! I wish us the people can make enough noise about this issue that big tech companies will stop chipping away at our freedoms :(
